services:
  nginx:
    image: ivandreyv/nginx-alpine:$TAG
    read_only: true
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    tmpfs:
      - /var/lib/nginx/tmp/
      - /run/nginx/

